### PR TITLE
WIP: storybook as playground

### PR DESCRIPTION
**Pull request by rudnitskih**

### CODE REVIEW

**Comment by NickVlasov** [comment]
If you install dependencies with `npm` instead of `yarn` storybook build will fail cause it will use `css-loader` version(^3.0.0) from storybook, not `css-loader` from haste-playable-preset (loader version ^0.28.11.
One of the solutions was to always install dependencies with `yarn` instead of `npm`, but I think that it's not a good DX. Added the same version of `css-loader` to dev deps as in `haste-playable-preset`

**Comment by rudnitskih** [comment]
@NickVlasov nice catch!

**Comment by rudnitskih** [comment]
@NickVlasov can you share a link -- interesting to see result.

**Comment by NickVlasov** [comment]
@rudnitskih Link for what? Storybook is not deployed anywhere, could be launched just locally. Storybook playground didn't change visually since your changes

**Comment by rudnitskih** [comment]
@NickVlasov got it, thought you made something additional. Why don't publish it and add a link to documentation website?

**Pull request merged**
